# Generated by Django 3.2.8 on 2021-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211202_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
